export const tvs = [
  {
    'id': 1,
    'service_name': "Samsung 55” 4K Smart TV",
    'price': '28,999',
    'description': "A high-definition QLED display offering vibrant 4K visuals and smart connectivity features.",
    'resolution': "4K",
    'size': 55,
    'sample_image': "/images/samsung55.jpg",
    'rating': 4.5,
    'numReviews': 68,
    'duration': '2.5 hours',
    'expert': 'John Doe',
  },
  {
    'id': 2,
    'service_name': "LG 65” OLED TV",
    'price': '75,999',
    'description': "A premium large-screen 4K OLED television known for deep blacks and exceptional color contrast.",
    'resolution': "4K",
    'size': 65,
    'sample_image': "/images/lg65.jpg",
    'rating': 4.0,
    'numReviews': 74,
    'duration': '3 hours',
    'expert': 'Jane Smith',
  },
  {
    'id': 3,
    'service_name': "Sony 43” LED TV",
    'price': '19,999',
    'description': "A compact Full HD LED screen perfect for smaller rooms without sacrificing picture quality.",
    'resolution': "Full HD",
    'size': 43,
    'sample_image': "/images/sony43.jpg",
    'rating': 4.0,
    'numReviews': 91,
    'duration': '2 hours',
    'expert': 'Sarah Spit',
  },
];

export const audioDevices = [
  {
    'id': 1,
    'service_name': "JBL Soundbar 2.1",
    'price': '8,999',
    'description': "A sleek, space-saving soundbar and wireless subwoofer combo designed to enhance your home cinema audio.",
    'sample_image': "/images/JBLbar.jpg",
    'rating': 4.5,
    'numReviews': 62,
    'duration': '4 hours',
    'expert': 'Fred Johnson',
  },
  {
    'id': 2,
    'service_name': "Sony Home Theater System",
    'price': '15,999',
    'description': "A comprehensive multi-speaker surround sound setup for an immersive, theater-like listening experience.",
    'sample_image': "/images/hometheater.jpg",
    'rating': 5.0,
    'numReviews': 97,
    'duration': '4 hours',
    'expert': 'Paul Lee',
  },
];

export const setups = [
  {
    'id': 1,
    'service_name': "Budget Setup",
    'description': "An affordable entry-level pairing of a basic TV and soundbar, ideal for small living spaces or bedrooms.",
    'priceRange': "10,000 - UNDER",
    'sample_image': "/images/budgetsetup.jpg",
    'rating': 4.0,
    'numReviews': 123,
    'duration': '5 hours',
    'expert': 'Kyle Brown',
  },
  {
    'id': 2,
    'service_name': "Gaming Setup",
    'description': "A high-performance bundle featuring a 4K TV, gaming console, and dedicated speakers for the ultimate gaming experience.",
    'priceRange': "20,000 - ₱50,000",
    'sample_image': "/images/gamingsetup.jpg",
    'rating': 4.5,
    'numReviews': 106,
    'duration': '6 hours',
    'expert': 'Neil Davis',
  },
];